# Site settings
title: "{ David Arias }"
email: arias1011@gmail.com
description: "Personal site of David Arias"
baseurl: ""
url: "https://www.davidarias.net"
twitter_username: DarthCoder1011
github_username:  davidarias
instagram_username: davidarias1010

# Build settings
markdown: kramdown
permalink: pretty
future: True
paginate: 5
paginate_path: "/blog/page/:num/"

gems: [jekyll-paginate]
plugins: [jekyll-paginate]
